import os

POSTGRESQL_HOST = os.environ["POSTGRESQL_HOST"]
POSTGRESQL_PORT = os.environ["POSTGRESQL_PORT"]
POSTGRESQL_USER = os.environ["POSTGRESQL_USER"]
POSTGRESQL_PASS = os.environ["POSTGRESQL_PASS"]
POSTGRESQL_DB = os.environ["POSTGRESQL_DB"]
